# adapt configuration to development environment within docker
url: https://staging.lernmoment.de
future: false

# Site owner
owner:
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

