# adapt configuration to development environment within docker
url: http://0.0.0.0:4000
future: true

include: []

# Site owner
owner:
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

